---

version: 2.1

defaults: &defaults
  working_directory: ~/truemail-go
  docker:
    - image: cimg/go:1.20.1

jobs:
  linters:
    docker:
      - image: golangci/golangci-lint:v1.51.1-alpine

    steps:
      - checkout

      - run:
          name: Installing linters
          command: |
                apk add --update npm shellcheck yamllint
                npm install --global --save-dev git+https://github.com/streetsidesoftware/cspell-cli markdownlint-cli lefthook
                cp .circleci/linter_configs/.lefthook.yml lefthook.yml

      - run:
          name: Running linters
          command: |
            lefthook run linters

  tests:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Running tests
          command: |
            gotestsum --format standard-verbose -- -coverprofile=coverage_report ./...

      - run:
          name: Creating coverage reports
          command: |
            mkdir -p /tmp/artifacts
            go tool cover -html=coverage_report -o coverage.html
            go tool cover -func=coverage_report -o coverage.txt
            mv coverage.html coverage.txt /tmp/artifacts

      - store_artifacts:
          name: Saving coverage artifacts
          path: /tmp/artifacts

      - run:
          name: Enforcing minimum code coverage
          command: |
            tail -1 /tmp/artifacts/coverage.txt | awk '{ exit (($NF == "100.0%") ? 0 : 1) }'

      - deploy:
          name: Uploading Codecov test coverage report
          command: |
            bash <(curl -s https://codecov.io/bash) -f coverage_report

  tag:
    <<: *defaults

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "f6:1c:3f:c6:bd:08:21:0b:2c:a9:0a:1f:7b:92:1d:00"

      - run:
          name: Publishing new tag to GitHub
          command: |
            ./.circleci/scripts/tag.sh

  release:
    <<: *defaults

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "f6:1c:3f:c6:bd:08:21:0b:2c:a9:0a:1f:7b:92:1d:00"

      - run:
          name: Publishing new release to GitHub, Go Packages
          command: |
            ./.circleci/scripts/release.sh truemail-rb truemail-go

workflows:
  build:
    jobs:
      - linters
      - tests
      - tag:
          requires:
            - linters
            - tests
          filters:
            branches:
              only: master
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
