version: 2.1

jobs:
  linters:
    docker:
      - image: golangci/golangci-lint:v1.50.1-alpine
    steps:
      - checkout
      - run: golangci-lint run

  test:
    docker:
      - image: cimg/go:1.19.3
    working_directory: ~/truemail-go
    steps:
      - checkout

      - run:
          name: Running tests with Gotestsum
          command: gotestsum --format standard-verbose -- -coverprofile=coverage_report ./...

      - run:
          name: Creating coverage reports
          command: |
            mkdir -p /tmp/artifacts
            go tool cover -html=coverage_report -o coverage.html
            go tool cover -func=coverage_report -o coverage.txt
            mv coverage.html coverage.txt /tmp/artifacts

      - store_artifacts:
          name: Saving coverage artifacts
          path: /tmp/artifacts

      - run:
          name: Enforcing minimum code coverage
          command: |
            tail -1 /tmp/artifacts/coverage.txt | awk '{ exit (($NF == "100.0%") ? 0 : 1) }'

      - deploy:
          name: Uploading Codecov test coverage report
          command: |
            bash <(curl -s https://codecov.io/bash) -f coverage_report

workflows:
  build:
    jobs:
      - linters
      - test
